#Data params
output_dir: "/home/anakuzne/exp/encodec_04_2023/saved_models"
data_path: "/data/common"
csv_path: "/home/anakuzne/utils/csvs/encodec_ds.csv"
mixture: False
standardize: False
exp_name: "encodec_ft_base_bw3_no_se"
finetune_model: "/home/anakuzne/projects/encodec_hy/encodec/ckpt/epoch1999_model.amlt"
#finetune_disc: "/home/anakuzne/projects/encodec_hy/encodec/ckpt/encodec_unstd_disc.amlt"
finetune_disc: False

#Training params
use_disc: True
disc_freq: 1
bandwidth: 3
batch_size: 1
freeze_enc: False
freeze_dec: False
sr: 16000

use_se_loss: False
lr_gen: 3e-4
lr_disc: 3e-4
debug: True